### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by mzolfaghari94** [sslab-gatech/apisan#6]
Hi,
I tried to apply apisan on qemu, but when I built the qemu using `apisan build make`, it used all of my 64GB memory and 200GB of the 256GB swap and stopped running. Is it common? What should I do?
Thanks

**Comment by jakkdu** [comment]
Hi.
It depends on the program that you compile.
I didn't run the QEMU using APISan.
But it spends too much memory in one file, you can just kill the process.
It will lose some information related to the file,
since APISan uses statistical information of code, it will work with incomplete information.
Thanks.
