### ISSUE TITLE
Traces generated by symbolic execution

### ISSUE THREAD

**Issue by lc3412** [sslab-gatech/apisan#9]
Hi,

After reading the paper, I like your job actually. However, during the process of reading source code, I have met several confusions.

- First: where are the traces after symbolic execution? If convenient, would you mind saying its address in source code? 

- Second: Where are the functions mentioned in the paper, such as returnValueContexts, argRelationContexts? I couldn't find them in source code.  If convenient, would you mind saying its address?

- Third: Apisan is implement on the basis of clang and llvm. If convenient, would you mind saying the changes you've made on the framework?

Sincerely,
Liz

**Comment by jakkdu** [comment]
Hi, Liz.
1. We use clang's symbolic execution. After you run build, you can find *.as files. These are traces for symbolic execution. The code is [here](
https://github.com/sslab-gatech/apisan/blob/master/llvm/tools/clang/lib/StaticAnalyzer/Checkers/SymExecExtractor.cpp).

2. In paper, we used camel case, but actually use snake case since we implemented checkers with python. You can find checkers in the [checker directory](https://github.com/sslab-gatech/apisan/blob/master/analyzer/apisan/check/). For example, in [argument checker](https://github.com/sslab-gatech/apisan/blob/master/analyzer/apisan/check/argument.py), you can find `ArgContext`.

3. Sorry. I cannot remember all changes that I made. But most of changes are related to the `SymExecExtractor.cpp`. I think you can diff our clang with the original one even though I cannot remember its exact version. But I think there is fingerprinting information in the directory. 

Thank you.
